#define GRAPHICS_OUTPUT_PROTOCOL_ROTATE_PROTOCOL_GUID \
    { 0xda62085c, 0x96e4, 0x4345, { 0xa3, 0xb0, 0x98, 0x89, 0xda, 0xf3, 0x16, 0xb7 } }


typedef enum 
{
    Rotate0 = 0,
    Rotate90 = 1,
    Rotate180 = 2,
    Rotate270 = 3
} ROTATE_SCREEN;

typedef struct _GRAPHICS_OUTPUT_PROTOCOL_ROTATE_PROTOCOL GRAPHICS_OUTPUT_PROTOCOL_ROTATE_PROTOCOL;

typedef
EFI_STATUS
(EFIAPI *GRAPHICS_OUTPUT_PROTOCOL_ROTATE_GET_ROTATION)(
  IN  GRAPHICS_OUTPUT_PROTOCOL_ROTATE_PROTOCOL  *This,
  IN  ROTATE_SCREEN                             *Rotation
  );

typedef
EFI_STATUS
(EFIAPI *GRAPHICS_OUTPUT_PROTOCOL_ROTATE_SET_ROTATION)(
  IN  GRAPHICS_OUTPUT_PROTOCOL_ROTATE_PROTOCOL  *This,
  IN  ROTATE_SCREEN                             Rotation
  );

struct _GRAPHICS_OUTPUT_PROTOCOL_ROTATE_PROTOCOL
{
    GRAPHICS_OUTPUT_PROTOCOL_ROTATE_GET_ROTATION GetRotation;
    GRAPHICS_OUTPUT_PROTOCOL_ROTATE_SET_ROTATION SetRotation;
};


extern EFI_GUID gGraphicsOutputProtocolRotateProtocolGuid;


